### ISSUE TITLE
When opening the RFUniverse Unity side repository in the Unity editor, enter safe mode

### ISSUE THREAD

**Issue by sasusau** [mvig-robotflow/rfuniverse#13]
Hello, in the process of reproducing the Franka Robotics RL environment tutorial based on the Multipahysics RL scenario tutorial, the first step is to build the scene in Unity. However, when opening the RFUniverse Unity side repository in the Unity editor, enter safe mode. Can you provide me with a solution? Thank you.

**Comment by ghzh26252** [comment]
Just click the [Ignore] button, go to the editor and continue.
