### ISSUE TITLE
How can I open the camera on continuously？

### ISSUE THREAD

**Issue by xiaolijz** [mvig-robotflow/rfuniverse#14]
Hi, I want to know how to keep the camera continuously active. In a code cycle, `camera.GetRGB()` function just can get a frame, but the action of robot is continuously, so I can't capture the entire action. How can I solve this problem?

**Comment by ghzh26252** [comment]
In your loop, call GetRGB() before each step
If you use WaitDo(), you can view the source code of the method and write your own loop

**Comment by xiaolijz** [comment]
> In your loop, call GetRGB() before each step If you use WaitDo(), you can view the source code of the method and write your own loop
Thank you for your reply, I have solved this problem. By the way, I want to know is there an operations manual for this simulation environment? For example, how to make a robotic arm draw a circle?

**Comment by ghzh26252** [comment]
You can calculate the interpolation yourself to make the robot draw a circle, Refer to our example scripts and API documentation

**Comment by xiaolijz** [comment]
> You can calculate the interpolation yourself to make the robot draw a circle, Refer to our example scripts and API documentation

Thank you for your reply, it is very helpful. By the way, I want to know how to use a robotic gripper to pick up a piece of clothing, I passed the coordinates of the particles to the end effector of the robotic arm, but I haven't been successful after several attempts.

**Comment by ghzh26252** [comment]
Does not support physical grabbing of cloth
Refer to the [test_cloth_attach ](https://github.com/robotflow-initiative/pyrfuniverse/blob/main/test/pyrfuniverse_test/test/test_cloth_attach.py) script and use the AddAttach API to simulate
