### ISSUE TITLE
Linux system common loading model error fixes

### ISSUE THREAD

**Issue by ghzh26252** [mvig-robotflow/rfuniverse#3]
When you encounter the following error while using the LoadMesh / LoadURDF API on a Linux system:

```
AssimpException: Error loading unmanaged library from path: xxx/RFUniverse_Data/Plugins/libassimp.so
```

Do the following to try to fix it:

1.Add a link to the "libdl.so" library:
`sudo ln -s /lib/x86_64-linux-gnu/libdl.so.2 /lib/x86_64-linux-gnu/libdl.so`

2.Install the "libminizip" module:
`sudo apt install minizip`

**Comment by Eirikalb** [comment]
This worked for me on Ubuntu 22.04 using Unity 2022.3.50f1 LTS. Thank you!
