### ISSUE TITLE
No visual appearances for YCB prefabs

### ISSUE THREAD

**Issue by Necolizer** [mvig-robotflow/rfuniverse#4]
I found that YCB prefabs only have their colliders but no appearances or textures. 

- Version: [this commit](https://github.com/mvig-robotflow/rfuniverse/commit/203335f509995279e6115fd1edfa2fe1b1966b29) of Unity Source Project (and also [v0.9.20](https://github.com/mvig-robotflow/rfuniverse/releases/tag/v0.9.20) Unity Source Project)
- Ubuntu 18.04
- Unity Editor vesion: 2022.3.9f1
- Code: Run [this script](https://github.com/mvig-robotflow/pyrfuniverse/blob/main/Test/test_save_obj.py) but just load the env:
```
import os
from pyrfuniverse.envs.base_env import RFUniverseBaseEnv
import pyrfuniverse.attributes as attr

env = RFUniverseBaseEnv(scene_file='SimpleYCBModel.json')

# model = []

# for i in env.attrs:
#     if type(env.attrs[i]) is attr.RigidbodyAttr:
#         model.append(i)

# env.ExportOBJ(model, os.path.abspath('../Mesh/scene_mesh.obj'))

env.Pend()
```
- Results: 
![Screenshot from 2023-10-18 11-47-01](https://github.com/mvig-robotflow/rfuniverse/assets/58028682/90f97a14-1ee5-4e6d-90e3-431b92f6b298)

![Screenshot from 2023-10-18 11-47-24](https://github.com/mvig-robotflow/rfuniverse/assets/58028682/e70f722b-f2cf-40ae-9176-2d8e1ea10f7e)

- Additional Info: It seems that all YCB prefabs' meshes or materials are missing.
![Screenshot from 2023-10-18 11-58-14](https://github.com/mvig-robotflow/rfuniverse/assets/58028682/cd5e309f-5f4b-447c-9dcf-e6a73d07d8b0)

**Comment by ghzh26252** [comment]
The raw resources of the YCB dataset and IGibson Scene take up too much space, so they are not included in the open source project.
The solution is:
Package them into a .unitypackage and upload to the release for developers to download.
Thanks to using RFUniverse, we will update the documentation as soon as it is completed.

**Comment by ghzh26252** [comment]
> The raw resources of the YCB dataset and IGibson Scene take up too much space, so they are not included in the open source project. The solution is: Package them into a .unitypackage and upload to the release for developers to download. Thanks to using RFUniverse, we will update the documentation as soon as it is completed.

[Dataset unitypackage](https://github.com/mvig-robotflow/rfuniverse/releases/tag/Dataset)
