### ISSUE TITLE
issue about edit mode -- v0.10.2.1

### ISSUE THREAD

**Issue by syw-robotics** [mvig-robotflow/rfuniverse#5]
- I deployed rfuniverse v0.10.2.1 on linux, it seems that the key "CTRL" corresponds to the lens descending instead of "SHIFT.

- BTW, when I run the software, I am wondering what causes "Invalid scalable image specified" in DebugWindow, although it does not seem affect normal usage at all.

![image](https://github.com/mvig-robotflow/rfuniverse/assets/84261527/49eab22f-e3e4-4014-be73-b5214e7db001)

------------------------------------------------------------

- 我在 Linux 上部署了 rfuniverse v0.10.2.1，似乎键“CTRL”对应镜头下降而不是“SHIFT”，文档中写的是SHIFT键。

- 另外哥们有点好奇 DebugWindow 中的“Invalid scalable image specified”，似乎不影响正常使用但看起来好怪（）。

感谢捏，支持国产仿真软件，加油加油

**Comment by Necolizer** [comment]
我这边运行发布版，也同样是ctrl对应主摄像机机位下降，我觉得是由于发布版中给摄像机挂了这个[script](https://github.com/mvig-robotflow/rfuniverse/blob/203335f509995279e6115fd1edfa2fe1b1966b29/Assets/RFUniverse/Runtime/Scripts/Utils/FreeCamera.cs)，所以它是WSAD+space+left ctrl的控制键。我没看到文档说ctrl对应shift？

以及感觉发布版的edit mode我个人不太会用，创建物品点了后什么都没发生，后来我就直接用了开源的unity工程（

**Comment by syw-robotics** [comment]
感谢大佬；

同edit mode不会用；

md和pdf的manual里面写的是shift控制下降，可能是还没更新；

![image](https://github.com/mvig-robotflow/rfuniverse/assets/84261527/a3447f82-c3ff-46ca-bcbe-12779f7ae6a9)

**Comment by ghzh26252** [comment]
Thank you for finding the problem, this documentation hasn't been updated for a long time, and there are some minor feature tweaks that haven't been updated in time.
For the `Invalid scalable image specified` warning in the DebugWindow, it does not affect the use, please ignore them and will be removed in the future

**Comment by syw-robotics** [comment]
Thanks so much for the reply! Expecting to explore more about RFUniverse!
