### ISSUE TITLE
Questions about SetParent and local_position

### ISSUE THREAD

**Issue by hxm1150310617** [mvig-robotflow/rfuniverse#7]
Hi, i have confusions about the value of self.data[‘local_position’]. My purpose is to create a mesh and a camera, by setting the transforms of the camera and the mesh seperatly and setting the mesh to the camera's parent, i can get the straight transform matrix from the mesh coordinate to the camera coordinate.

HERE are my STEPS:
1)Firstly I created a mesh from file using env.LoadMesh function.
2)I use : 

                         `mesh.SetTransform(
                                 position=[0, 0, 0],
                                 rotation=[0, 0, 0],
                                 scale=[0.035, 0.035, 0.035], is_world=True
                          )
                          env.step()`

 to set the position and rotation of the loaded mesh.
3) I created the camera, and set the parent with code:
                                  `camera.SetParent(parent_id=mesh.id)`
    then i set the position and rotation of camera by 
                                   `camera.SetTransform(
                                                 position=[5,2,5 ], rotation=[ 0, 200,0 ], is_world=True)
                                   env.step()`

HERE are my QUESTIONS:
1) After doing the aforementioned STEPS, i use the env.SaveScene to save the scene, but the saved json file doesn't record the "parenID" correctlly, 

        {"parentID": -1,
        "parentName": "box1.obj"}

parentID equls to -1 in all cameras, but the parentName are all correct. **Is there any STEP that I did wrong during setting the parent?**
2)I use the camera.data['local_position'] and camera.data['local_rotation'] to get the local tansforms, but the local_position seems to be wrong.  With the params using in STEPS, i get the 
                               **camera.data['local_position']=[142.85714721679688, 56.48296356201172, 142.85775756835938]**
         and the 
                               **camera.data['local_rotation']=[-0.0005285008228383958, 200.0000457763672, -0.00027268179110251367]**
        **the local_rotation seems to be reasonable, but the local_position is too large to me. Should it equl to [5, 2, 5] or should it be much  smaller? My guess is because i set the scale factor of the parent mesh, so i need to multipy the scale factor seperately in [x,y,z]**

**Comment by hxm1150310617** [comment]
By the way, I also want to know how to caculate the local_position and the local_rotation. Can they be caculated by the rotation and the position of parent mesh and them of the child camera?

**Comment by ghzh26252** [comment]
Thank you for your feedback, I will respond to your questions one by one:

1.After verification, it's indeed a bug that the parentID has not been properly stored, which will be fixed in the next version.

2.Nevertheless, SavaScene still cannot save external models loaded by the LoadMesh interface. For scenes managed by Json files, only the built-in objects of RFUniverse (objects created by InstanceObject) are supported. So please do not use SaveLoad and LoadScene to manage your scenes for the time being, and implement it with code instead.

3.As you understand, the camera has been put in a parent object with scale, so its coordinate will be the coordinate of the parent object:
142.85714721679688*0.035≈5

4.I'm providing a piece of code to help you understand the transformation between Position and Quaternion in local and world space:
```
import numpy as np
from quaternion.numpy_quaternion import quaternion
from pyrfuniverse.envs.base_env import RFUniverseBaseEnv
import pyrfuniverse.attributes as attr

env = RFUniverseBaseEnv()

cube = env.InstanceObject("GameObject_Box", attr_type=attr.GameObjectAttr)
cube.SetTransform(position=[0, 1, 0], rotation=[25, 85, 175], scale=[0.035, 0.035, 0.035], is_world=True)
camera = env.InstanceObject("Camera", attr_type=attr.CameraAttr)
camera.SetParent(cube.id, "GameObject_Box")
camera.SetTransform(position=[0, 2, 0], rotation=[45, 30, 60], is_world=True)
env.step()


cube_matrix = np.array(cube.data['local_to_world_matrix'])
camera_world_pos = np.array(camera.data['position'])
camera_local_pos = np.array(camera.data['local_position'])

print("camera world_pos")
print(camera_world_pos)
print("camera local_pos")
print(camera_local_pos)
camera_local_pos = np.append(camera_local_pos, 1)
print("camera world_pos form parent matrix")
print(np.dot(cube_matrix, camera_local_pos))

print("-----------------------------------------------")

cube_world_qua = cube.data['quaternion']
camera_world_qua = camera.data['quaternion']
camera_local_qua = camera.data['local_quaternion']

cube_world_qua = quaternion(cube_world_qua[3], cube_world_qua[0], cube_world_qua[1], cube_world_qua[2])
camera_world_qua = quaternion(camera_world_qua[3], camera_world_qua[0], camera_world_qua[1], camera_world_qua[2])
camera_local_qua = quaternion(camera_local_qua[3], camera_local_qua[0], camera_local_qua[1], camera_local_qua[2])

print("camera world_qua")
print(camera_world_qua)
print("camera local_qua")
print(camera_local_qua)
print("camera world_qua form parent qua")
print(cube_world_qua * camera_local_qua)


env.Pend()
env.close()
```

**Comment by hxm1150310617** [comment]
Thanks so much for your replying!  It helps a lot for me to understand! Also I have some new QUESTIONS about the code provided.
QUESTIONS:
1) I delete the 'camera.SetParent(cube.id, "GameObject_Box")', and still I can get the 'cube_matrix = np.array(cube.data['local_to_world_matrix'])'. And the value of the 'local_to_world_matrix' is:
`[[-0.00175457 -0.01494515  0.03160006  0.        ]
 [ 0.00276465 -0.03160007 -0.01479164  1.        ]
 [ 0.0348465   0.00175458  0.00276465  0.        ]
 [ 0.          0.          0.          1.        ]]
`
I can tell the right row [0. , 1., 0.] is the position we set for the cude before. **So does it mean that the top-left 3x3 matrix is the rotation matrix of the cube? Which means the rotation matrix should match to the rotation we set before(rotation=[25, 85, 175])?**
2) **Is it the same condition in 'cube_world_qua = cube.data['quaternion']'?**
3) If so, I assumed that the 'cube_world_qua' should be converted to the rotation=[25, 85, 175]. However, I tried the quaternion2euler method(which is defined below) to try to convert the 'cube_world_qua' to the rotation and never get the same result as [25, 85, 175].
`         from scipy.spatial.transform import Rotation as R
          def quaternion2euler(quaternion):
               r = R.from_quat(quaternion)
               euler = r.as_euler('zyx', degrees=True)
               return euler
          a = camera_world_qua[3]
          b = camera_world_qua[0]
          c = camera_world_qua[1]
          d = camera_world_qua[2]
          cube_qua_world_list = [a, b, c, d]
          print(quaternion2euler(cube_qua_world_list))`
I tried 'xyz', 'xzy', 'yxz', 'yzx', 'zxy', 'zyx' sequences and get all results different from [25, 85, 175]. I am so so so so so confused about it.

**Comment by hxm1150310617** [comment]
Thanks so much for your replying! It helps a lot for me to understand! Also I have some new QUESTIONS about the code provided.
QUESTIONS:

1) I delete the 'camera.SetParent(cube.id, "GameObject_Box")', and still I can get the 'cube_matrix = np.array(cube.data['local_to_world_matrix'])'. And the value of the 'local_to_world_matrix' is:

```

_[[-0.00175457 -0.01494515  0.03160006  0.        ] 
 [ 0.00276465 -0.03160007 -0.01479164  1.        ]
  [ 0.0348465   0.00175458  0.00276465  0.        ] 
 [ 0.          0.          0.          1.        ]]_ 

```
I can tell the right row [0. , 1., 0.] is the position we set for the cude before. **So does it mean that the top-left 3x3 matrix is the rotation matrix of the cube? Which means the rotation matrix should match to the rotation we set before(rotation=[25, 85, 175])?**

2)    **Is it the same condition in 'cube_world_qua = cube.data['quaternion']'?**

3)    If so, I assumed that the 'cube_world_qua' should be converted to the rotation=[25, 85, 175]. However, I tried the quaternion2euler method(which is defined below) to try to convert the 'cube_world_qua' to the rotation and never get the same result as [25, 85, 175].
```
           from scipy.spatial.transform import Rotation as R 
           def quaternion2euler(quaternion):
                 r = R.from_quat(quaternion) 
                euler = r.as_euler('zyx', degrees=True) 
                return euler 
           a = camera_world_qua[3] 
           b = camera_world_qua[0] 
           c = camera_world_qua[1] 
           d = camera_world_qua[2] 
           cube_qua_world_list = [a, b, c, d] 
           print(quaternion2euler(cube_qua_world_list))
```
**I tried 'xyz', 'xzy', 'yxz', 'yzx', 'zxy', 'zyx' sequences and get all results different from [25, 85, 175]. I am so so so so so confused about it.**

**Comment by ghzh26252** [comment]
1.Yes, the local_to_world_matrix is the 4*4 pose matrix used in other simulation applications.

2.`cube.data['quaternion']`,`cube.data['rotation']`, and `np.array(cube.data['local_to_world_matrix'])[:3,:3]` are respectively the quaternion, Euler angles, and rotation matrix of the cube in world space, all of which represent the rotation of the cube.

3.The conversion between Euler angles and quaternions is differentiated by the left and right-hand coordinate, with RFUniverse using the left-hand coordinate from Unity. In contrast, scipy's as_euler uses the right-hand coordinate. RFUniverse provides its conversion functions for Euler angles and quaternions.
```
import pyrfuniverse.utils.rfuniverse_utility as utility
cube_world_qua = cube.data['quaternion']
cube_world_eul = utility.UnityQuaternionToEular(cube_world_qua)
print(cube_world_qua)
print(cube_world_eul)
```

**Comment by hxm1150310617** [comment]
Thank you so much!! It really helps a lot for a beginner to understand. Thanks again for your patience.
