### ISSUE TITLE
After starting DRL training for hours, the system freezes, RFUniverse quits and python throws out "Connection reset by peer"

### ISSUE THREAD

**Issue by Necolizer** [mvig-robotflow/rfuniverse#8]
- OS: Ubuntu 18.04
- Version: A customized release version built from my customized Unity source code. I also replicate the same problem with your [RFUniverse_v0.12.2](https://github.com/mvig-robotflow/rfuniverse/releases/tag/v0.12.2) release version.
- Problem Description: 

I wrote a DRL training project based on RFUniverse. It is used to train the arm with gripper to grasp one bottle (from AKB-48 dataset) ramdonly positing on the ground. The model takes an RGB image and the joint_position args as input, then outputs the target position & orientation the gripper should reach (via IK). The training code is based on torch and stable-baseline 3.

The thing went well at the beginning of the training. But after several hours (over 3h), the OS froze, even out of mouse and keyboard control. Then when it resumed, the RFUniverse program quitted. Meanwhile, Python threw out the error "Connection reset by peer", which indicated that the TCP/IP connection failed due to the shutdown.

I have tried finding the crux myself but wind up failure. 
1. It seems the problem is NOT related to my customized C# code and building process, since I replicate that with your [RFUniverse_v0.12.2](https://github.com/mvig-robotflow/rfuniverse/releases/tag/v0.12.2) release version (with the provided franka_panda robot).
2. Use "SetJointPosition" instead of "IKTargetDoMove"/"IKTargetDoRotateQuaternion". But the problem still exists.
3. The problem is NOT related to the number of the created env. If I create 2 RFUniverse programs during training, the system still freezes. When it resumes, one of the programs quits, and the training procedure stops.

- Code: I temporarily make my repo public, here's [the link](https://github.com/Necolizer/rf_grasp). The script most related to the problem I believe may be [the env part](https://github.com/Necolizer/rf_grasp/blob/main/env/elfin_ag145_env.py).

**Comment by ghzh26252** [comment]
While the RFUniverse program is running, does the memory usage keep increasing?
Can you provide me with the Log file after the program crashed? Please see the official documentation for its location:
https://docs.unity3d.com/Manual/LogFiles.html

**Comment by Necolizer** [comment]
Logs of two crashed runs:
https://github.com/Necolizer/rf_grasp/blob/main/unitylogs/Player.log
https://github.com/Necolizer/rf_grasp/blob/main/unitylogs/Player-prev.log

Now I begin another run to check the memory usage. I'll tell you later.

**Comment by Necolizer** [comment]
Yes the memory usage of `RFUniverse.x86_64` goes up during training. But how can i fix that?

**Comment by ghzh26252** [comment]
This is likely caused by a memory leak, and I need to investigate this issue. It's recommended to make the following changes to temporarily avoid the problem:
1.Try to minimize the deletion and import of objects and URDFs, restoring their states through python api.
2.Restart the RFUniverse program after it has been running for a while to clear the leaked memory.

**Comment by ghzh26252** [comment]
The latest version 0.12.4 has fixed this memory leak. Please observe the memory usage after updating.

**Comment by Necolizer** [comment]
Thx for your attention and help.
